=== nordcraftengine/nordcraft/packages/lib/schemas/libAction.schema.json
{
  "$id": "libAction.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Lib action",
  "description": "A builtin action in the Nordcraft runtime",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "minLength": 1
    },
    "description": {
      "type": "string",
      "minLength": 1
    },
    "group": {
      "type": "string",
      "enum": [
        "cookies",
        "debugging",
        "events",
        "local_storage",
        "navigation",
        "session_storage",
        "sharing",
        "timers"
      ]
    },
    "deprecated": {
      "type": "boolean",
      "description": "Whether this action is deprecated",
      "optional": true
    },
    "supercededBy": {
      "type": "string",
      "description": "The name of the action that supersedes this action",
      "optional": true
    },
    "arguments": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": { "type": "string", "minLength": 1 },
          "description": { "type": "string", "minLength": 1 },
          "type": {
            "type": "any"
          },
          "formula": { "$ref": "Formula" },
          "required": ["name", "description", "type"]
        }
      }
    }
  },
  "required": ["name", "description", "group"],
  "additionalProperties": true
}

=== nordcraftengine/nordcraft/packages/lib/actions/deleteFromLocalStorage/action.json
{
  "$schema": "../../schemas/libAction.schema.json",
  "name": "Delete from local storage",
  "description": "Delete a value from local storage (if found) based on the provided key.",
  "group": "local_storage",
  "arguments": [
    {
      "name": "Key",
      "description": "The key in local storage to delete.",
      "type": { "type": "String" },
      "formula": {
        "type": "value",
        "value": ""
      }
    }
  ]
}

=== nordcraftengine/nordcraft/packages/lib/actions/gotToURL/action.json
{
  "$schema": "../../schemas/libAction.schema.json",
  "name": "Go to URL",
  "description": "Navigate to a specified URL.",
  "group": "navigation",
  "arguments": [
    {
      "name": "URL",
      "description": "The URL to navigate to.",
      "type": { "type": "String" },
      "formula": {
        "type": "value",
        "value": "https://example.com"
      }
    }
  ]
}

=== nordcraftengine/nordcraft/packages/lib/actions/share/action.json
{
  "$schema": "../../schemas/libAction.schema.json",
  "name": "Share",
  "description": "Share data with title, text, and/or URL using the Navigator.share API.",
  "group": "sharing",
  "arguments": [
    {
      "name": "URL",
      "description": "The URL to share.",
      "type": { "type": "String" },
      "formula": { "type": "value", "value": null }
    },
    {
      "name": "Title",
      "description": "The title to share.",
      "type": { "type": "String" },
      "formula": { "type": "value", "value": null }
    },
    {
      "name": "Text",
      "description": "The text to share.",
      "type": { "type": "String" },
      "formula": { "type": "value", "value": null }
    }
  ]
}

=== nordcraftengine/nordcraft/packages/lib/actions/focus/action.json
{
  "$schema": "../../schemas/libAction.schema.json",
  "name": "Focus",
  "description": "Move focus to a DOM element.",
  "group": "events",
  "arguments": [
    {
      "name": "Element",
      "description": "The DOM element that should receive focus.",
      "type": {
        "type": "Element"
      },
      "formula": {
        "type": "value",
        "value": null
      }
    },
    {
      "name": "Prevent scroll",
      "description": "Prevent scrolling to the focused element.",
      "type": {
        "type": "String"
      },
      "formula": {
        "type": "value",
        "value": null
      }
    }
  ]
}

=== nordcraftengine/nordcraft/packages/lib/actions/deleteFromSessionStorage/action.json
{
  "$schema": "../../schemas/libAction.schema.json",
  "name": "Delete from session storage",
  "description": "Delete a value from session storage (if found) based on the provided key.",
  "group": "session_storage",
  "arguments": [
    {
      "name": "Key",
      "description": "The key in session storage to delete.",
      "type": { "type": "String" },
      "formula": {
        "type": "value",
        "value": ""
      }
    }
  ]
}

=== nordcraftengine/nordcraft/packages/lib/actions/copyToClipboard/action.json
{
  "$schema": "../../schemas/libAction.schema.json",
  "name": "Copy to clipboard",
  "description": "Copy contents to the clipboard.",
  "group": "sharing",
  "arguments": [
    {
      "name": "Value",
      "description": "The value you want to copy.",
      "type": { "type": "String" },
      "formula": {
        "type": "value",
        "value": "<Param Value>"
      }
    }
  ]
}

=== nordcraftengine/nordcraft/packages/lib/actions/saveToSessionStorage/action.json
{
  "$schema": "../../schemas/libAction.schema.json",
  "name": "Save to session storage",
  "description": "Save a provided key/value to session storage by JSON encoding the value.",
  "group": "session_storage",
  "arguments": [
    {
      "name": "Key",
      "description": "The key to be used in session storage.",
      "type": { "type": "String" },
      "formula": {
        "type": "value",
        "value": ""
      }
    },
    {
      "name": "Value",
      "description": "The value that should be saved in session storage. This can be anything that is serializable (String, Number, Boolean, Array or Object).",
      "type": { "type": "Any" },
      "formula": {
        "type": "value",
        "value": null
      }
    }
  ]
}

=== nordcraftengine/nordcraft/packages/lib/actions/saveToLocalStorage/action.json
{
  "$schema": "../../schemas/libAction.schema.json",
  "name": "Save to local storage",
  "description": "Save a provided key/value to local storage by JSON encoding the value.",
  "group": "local_storage",
  "arguments": [
    {
      "name": "Key",
      "description": "The key to be used in local storage.",
      "type": { "type": "String" },
      "formula": {
        "type": "value",
        "value": ""
      }
    },
    {
      "name": "Value",
      "description": "The value that should be saved in local storage. This can be anything that is serializable (String, Number, Boolean, Array or Object).",
      "type": { "type": "Any" },
      "formula": {
        "type": "value",
        "value": null
      }
    }
  ]
}
