=== nordcraftengine/nordcraft/packages/lib/schemas/libFormula.schema.json
{
  "$id": "libFormula.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Lib formula",
  "description": "A builtin formula in the Nordcraft runtime",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string",
      "const": "../../schemas/libFormula.schema.json"
    },
    "cache": {
      "type": "boolean"
    },
    "name": {
      "type": "string",
      "minLength": 1
    },
    "description": {
      "type": "string",
      "minLength": 1
    },
    "arguments": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": { "type": "string", "minLength": 1 },
          "description": { "type": "string", "minLength": 1 },
          "type": { "type": "object" },
          "formula": { "$ref": "/Formula" }
        },
        "required": ["name", "type"]
      }
    },
    "output": {
      "type": "object",
      "properties": {
        "description": { "type": "string", "minLength": 1 }
      }
    },
    "variableArguments": { "type": "boolean" }
  },
  "required": ["name", "description"],
  "additionalProperties": false
}

=== nordcraftengine/nordcraft/packages/lib/formulas/add/formula.json
{
  "$schema": "../../schemas/libFormula.schema.json",
  "name": "Add",
  "arguments": [
    {
      "name": "0",
      "description": "Number to be added.",
      "type": {
        "type": "Number"
      },
      "formula": {
        "type": "value",
        "value": 1
      }
    },
    {
      "name": "1",
      "type": {
        "type": "Number"
      },
      "description": "Number to be added.",
      "formula": {
        "type": "value",
        "value": 1
      }
    }
  ],
  "variableArguments": true,
  "description": "Get the sum of multiple numbers.",
  "output": {
    "description": "The sum of all the input numbers.",
    "type": {
      "type": "Number"
    }
  }
}

=== nordcraftengine/nordcraft/packages/lib/formulas/every/formula.json
{
  "$schema": "../../schemas/libFormula.schema.json",
  "name": "Every",
  "description": "Run a formula returns for all items in an Array.",
  "arguments": [
    {
      "name": "Array",
      "formula": {
        "type": "value",
        "value": null
      },
      "description": "The array of items to evaluate.",
      "type": {
        "type": "Array"
      }
    },
    {
      "name": "Formula",
      "isFunction": true,
      "formula": {
        "type": "path",
        "path": ["Args", "item"]
      },
      "description": "Predicate formula for evaluating each item.",
      "type": {
        "type": "Formula"
      }
    }
  ],
  "output": {
    "description": "Returns True if the predicate formula returns true for all items in the Array, otherwise False.",
    "type": {
      "type": "Array"
    }
  }
}

=== nordcraftengine/nordcraft/packages/lib/formulas/isServer/formula.json
{
  "$schema": "../../schemas/libFormula.schema.json",
  "name": "Is Server",
  "description": "Get information about whether formulas are currently evaluated server-side or client-side.",
  "arguments": [],
  "output": {
    "description": "Returns True if formulas are evaluated server-side, and False if formulas are evaluated client-side.",
    "type": {
      "type": "Boolean"
    }
  }
}

=== nordcraftengine/nordcraft/packages/lib/formulas/takeLast/formula.json
{
  "$schema": "../../schemas/libFormula.schema.json",
  "name": "Take last",
  "description": "Take items from the end of an Array or String.",
  "arguments": [
    {
      "name": "Array",
      "formula": {
        "type": "value",
        "value": null
      },
      "description": "The input value.",
      "type": {
        "type": "Array \\| String"
      }
    },
    {
      "name": "Count",
      "formula": {
        "type": "value",
        "value": 1
      },
      "description": "Number of items to take.",
      "type": {
        "type": "Number"
      }
    }
  ],
  "output": {
    "description": "The last items from the Array or String.",
    "type": {
      "type": "Array \\| String"
    }
  }
}

=== nordcraftengine/nordcraft/packages/lib/formulas/lastIndexOf/formula.json
{
  "$schema": "../../schemas/libFormula.schema.json",
  "name": "Last Index of",
  "description": "Search an Array or String to find the index of the last occurrence of a specified item or substring.",
  "arguments": [
    {
      "name": "Array",
      "formula": {
        "type": "value",
        "value": ""
      },
      "description": "The value to search.",
      "type": {
        "type": "Array \\| String"
      }
    },
    {
      "name": "Item",
      "formula": {
        "type": "value",
        "value": ""
      },
      "description": "The item or substring to search for.",
      "type": {
        "type": "Any"
      }
    }
  ],
  "output": {
    "description": "If the item or substring exists in the Array, the last index of that item is returned. If the item is not found, -1 is returned.",
    "type": {
      "type": "Number"
    }
  }
}

=== nordcraftengine/nordcraft/packages/lib/formulas/findLast/formula.json
{
  "$schema": "../../schemas/libFormula.schema.json",
  "name": "Find Last",
  "description": "Search through an Array of items and apply a formula to each item, to return the last item where the formula returns True.",
  "arguments": [
    {
      "name": "Array",
      "formula": {
        "type": "value",
        "value": null
      },
      "description": "The array to search.",
      "type": {
        "type": "Array"
      }
    },
    {
      "name": "Formula",
      "isFunction": true,
      "formula": {
        "type": "path",
        "path": ["Args", "item"]
      },
      "description": "The predicate formula that each item in the Array is passed to.",
      "type": {
        "type": "Formula"
      }
    }
  ],
  "output": {
    "description": "The last item in the Array where the formula returns True. Returns Null if the predicate formula did not return True for any item.",
    "type": {
      "type": "Any"
    }
  }
}

=== nordcraftengine/nordcraft/packages/lib/formulas/getFromSessionStorage/formula.json
{
  "$schema": "../../schemas/libFormula.schema.json",
  "name": "Get from Session Storage",
  "description": "Read a value from session storage with the provided key.\n If the value is a JSON string it is automatically parsed before it is returned.\nYou do not need to use the parseJSON formula",
  "cache": false,
  "arguments": [
    {
      "name": "Key",
      "formula": {
        "type": "value",
        "value": null
      },
      "description": "The key to read from session storage.",
      "type": {
        "type": "String"
      }
    }
  ],
  "output": {
    "description": "The value found in session storage.",
    "type": {
      "type": "Any"
    }
  }
}

=== nordcraftengine/nordcraft/packages/lib/formulas/capitalize/formula.json
{
  "$schema": "../../schemas/libFormula.schema.json",
  "name": "Capitalize",
  "description": "Capitalize a string: make the first letter uppercase whilst keeping the rest lowercase.",
  "arguments": [
    {
      "name": "String",
      "formula": {
        "type": "value",
        "value": "string"
      },
      "description": "An input String.",
      "type": {
        "type": "String"
      }
    }
  ],
  "output": {
    "description": "The capitalized String.",
    "type": {
      "type": "String"
    }
  }
}
