=== nordcraftengine/nordcraft/packages/lib/schemas/libFormula.schema.json
{
  "$id": "libFormula.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Lib formula",
  "description": "A builtin formula in the Nordcraft runtime",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string",
      "const": "../../schemas/libFormula.schema.json"
    },
    "cache": {
      "type": "boolean"
    },
    "name": {
      "type": "string",
      "minLength": 1
    },
    "description": {
      "type": "string",
      "minLength": 1
    },
    "arguments": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": { "type": "string", "minLength": 1 },
          "description": { "type": "string", "minLength": 1 },
          "type": { "type": "object" },
          "formula": { "$ref": "/Formula" }
        },
        "required": ["name", "type"]
      }
    },
    "output": {
      "type": "object",
      "properties": {
        "description": { "type": "string", "minLength": 1 }
      }
    },
    "variableArguments": { "type": "boolean" }
  },
  "required": ["name", "description"],
  "additionalProperties": false
}

=== nordcraftengine/nordcraft/packages/lib/formulas/timestamp/formula.json
{
  "$schema": "../../schemas/libFormula.schema.json",
  "name": "Timestamp",
  "description": "Get the timestamp from a Date, e.g. 1633462980000.",
  "arguments": [
    {
      "name": "Date",
      "description": "The date to get the timestamp from.",
      "type": {
        "type": "Date"
      },
      "formula": {
        "type": "value",
        "value": null
      }
    }
  ],
  "output": {
    "description": "The timestamp from the date input.",
    "type": {
      "type": "Number"
    }
  }
}

=== nordcraftengine/nordcraft/packages/lib/formulas/get/formula.json
{
  "$schema": "../../schemas/libFormula.schema.json",
  "name": "Get",
  "description": "Extract a value from an Object, Array or String at the specified path.",
  "arguments": [
    {
      "name": "Object",
      "formula": {
        "type": "value",
        "value": null
      },
      "description": "The Object, Array or String you want to extract an item from.",
      "type": {
        "type": "Array \\| Object \\| String"
      }
    },
    {
      "name": "Path",
      "formula": {
        "type": "value",
        "value": "Item"
      },
      "description": "The Path can be either a Number, a String, or an Array.",
      "type": {
        "type": "Array<String> \\| Number \\| String"
      }
    }
  ],
  "output": {
    "description": "The value found at the Path. If no value is found, this value of the output is Null.",
    "type": {
      "type": "Any"
    }
  }
}

=== nordcraftengine/nordcraft/packages/lib/formulas/currentURL/formula.json
{
  "$schema": "../../schemas/libFormula.schema.json",
  "name": "Current URL",
  "description": "Return the current URL of the browser. Use the \"Parse URL\" formula for working with the URL.",
  "arguments": [],
  "cache": false,
  "output": {
    "description": "The browser's current URL.",
    "type": {
      "type": "String"
    }
  }
}

=== nordcraftengine/nordcraft/packages/lib/formulas/lessThan/formula.json
{
  "$schema": "../../schemas/libFormula.schema.json",
  "name": "Less than",
  "description": "Compute if a value is smaller than another value.",
  "arguments": [
    {
      "name": "First",
      "formula": {
        "type": "value",
        "value": ""
      },
      "description": "First Number to be compared.",
      "type": {
        "type": "Number"
      }
    },
    {
      "name": "Second",
      "formula": {
        "type": "value",
        "value": ""
      },
      "description": "Second Number to be compared.",
      "type": {
        "type": "Number"
      }
    }
  ],
  "output": {
    "description": "Returns True if the First Number is smaller than the second Number, otherwise it returns False.",
    "type": {
      "type": "Boolean"
    }
  }
}

=== nordcraftengine/nordcraft/packages/lib/formulas/getHttpOnlyCookie/formula.json
{
  "$schema": "../../schemas/libFormula.schema.json",
  "name": "Get Http-Only Cookie",
  "description": "Get the value of an Http-Only cookie by name. This formula is only intended to be used server-side for SSR/proxied API requests to read Http-Only cookies.",
  "arguments": [
    {
      "name": "Cookie name",
      "formula": {
        "type": "value",
        "value": null
      },
      "description": "The name of the Http-Only cookie you want to get the value of.",
      "type": {
        "type": "String"
      }
    }
  ],
  "output": {
    "description": "The value of the cookie. If no cookie is found, this will return Null. If you use this formula client-side, it will return a placeholder template string.",
    "type": {
      "type": "String"
    }
  }
}

=== nordcraftengine/nordcraft/packages/lib/formulas/parseJSON/formula.json
{
  "$schema": "../../schemas/libFormula.schema.json",
  "name": "Parse JSON",
  "description": "Parse a String to JSON.",
  "arguments": [
    {
      "name": "JSON string",
      "formula": {
        "type": "value",
        "value": null
      },
      "description": "The String to be parsed.",
      "type": {
        "type": "String"
      }
    },
    {
      "name": "Date parsing",
      "formula": {
        "type": "value",
        "value": false
      },
      "description": "Whether to attempt parsing date strings to Date objects. This can have a significant impact on performance, so it is disabled by default.",
      "type": {
        "type": "Boolean"
      }
    }
  ],
  "output": {
    "description": "The parsed JSON value. If the input is not a valid String, this returns Null.",
    "type": {
      "type": "Any"
    }
  }
}

=== nordcraftengine/nordcraft/packages/lib/formulas/matches/formula.json
{
  "$schema": "../../schemas/libFormula.schema.json",
  "name": "Matches",
  "description": "Finds the (global) matches in a String based on a regular expression.",
  "arguments": [
    {
      "name": "Input",
      "formula": {
        "type": "value",
        "value": ""
      },
      "description": "The string to search for matches in.",
      "type": {
        "type": "String"
      }
    },
    {
      "name": "Regular expression",
      "formula": {
        "type": "value",
        "value": ""
      },
      "description": "The regular expression to use for matching.",
      "type": {
        "type": "String"
      }
    },
    {
      "name": "Global search",
      "formula": {
        "type": "value",
        "value": true
      },
      "description": "Test the regular expression against all possible matches in a string.",
      "type": {
        "type": "Boolean"
      }
    },
    {
      "name": "Case insensitive",
      "formula": {
        "type": "value",
        "value": false
      },
      "description": "Ignore case while attempting a match in a string.",
      "type": {
        "type": "Boolean"
      }
    },
    {
      "name": "Multi line",
      "formula": {
        "type": "value",
        "value": false
      },
      "description": "Treat multiline strings as multiple lines.",
      "type": {
        "type": "Boolean"
      }
    }
  ],
  "output": {
    "description": "An Array of Strings",
    "type": {
      "type": "Array"
    }
  }
}

=== nordcraftengine/nordcraft/packages/lib/formulas/minus/formula.json
{
  "$schema": "../../schemas/libFormula.schema.json",
  "name": "Minus",
  "description": "Subtract a Number from a Number.",
  "arguments": [
    {
      "name": "Minuend",
      "formula": {
        "type": "value",
        "value": 1
      },
      "description": "The number to subtract from.",
      "type": {
        "type": "Number"
      }
    },
    {
      "name": "Substrahend",
      "formula": {
        "type": "value",
        "value": 1
      },
      "description": "The number to subtract.",
      "type": {
        "type": "Number"
      }
    }
  ],
  "output": {
    "description": "The result of subtracting the Substrahend from the Minuend.",
    "type": {
      "type": "Number"
    }
  }
}
