=== nordcraftengine/nordcraft/packages/lib/schemas/libFormula.schema.json
{
  "$id": "libFormula.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Lib formula",
  "description": "A builtin formula in the Nordcraft runtime",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string",
      "const": "../../schemas/libFormula.schema.json"
    },
    "cache": {
      "type": "boolean"
    },
    "name": {
      "type": "string",
      "minLength": 1
    },
    "description": {
      "type": "string",
      "minLength": 1
    },
    "arguments": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": { "type": "string", "minLength": 1 },
          "description": { "type": "string", "minLength": 1 },
          "type": { "type": "object" },
          "formula": { "$ref": "/Formula" }
        },
        "required": ["name", "type"]
      }
    },
    "output": {
      "type": "object",
      "properties": {
        "description": { "type": "string", "minLength": 1 }
      }
    },
    "variableArguments": { "type": "boolean" }
  },
  "required": ["name", "description"],
  "additionalProperties": false
}

=== nordcraftengine/nordcraft/packages/lib/formulas/equals/formula.json
{
  "$schema": "../../schemas/libFormula.schema.json",
  "name": "Equals",
  "description": "Compute if values are identical.",
  "arguments": [
    {
      "name": "First",
      "formula": {
        "type": "value",
        "value": ""
      },
      "description": "First Value",
      "type": {
        "type": "Any"
      }
    },
    {
      "name": "Second",
      "formula": {
        "type": "value",
        "value": ""
      },
      "description": "Second Value",
      "type": {
        "type": "Any"
      }
    }
  ],
  "output": {
    "description": "Returns True if the input values are identical, otherwise False.",
    "type": {
      "type": "Boolean"
    }
  }
}

=== nordcraftengine/nordcraft/packages/lib/formulas/clamp/formula.json
{
  "$schema": "../../schemas/libFormula.schema.json",
  "name": "Clamp",
  "description": "Limit a value to a specified Min and Max value.",
  "arguments": [
    {
      "name": "Value",
      "type": {
        "type": "Number"
      },
      "formula": {
        "type": "value",
        "value": null
      },
      "description": "Number to round."
    },
    {
      "name": "Min",
      "type": {
        "type": "Number"
      },
      "description": "The smallest allowed Number.",
      "formula": {
        "type": "value",
        "value": 0
      }
    },
    {
      "name": "Max",
      "type": {
        "type": "Number"
      },
      "description": "The largest allowed Number.",
      "formula": {
        "type": "value",
        "value": 100
      }
    }
  ],
  "output": {
    "type": {
      "type": "Number"
    },
    "description": "Returns the input value if between the specified Min and Max. Otherwise, it returns the Min or Max value."
  }
}

=== nordcraftengine/nordcraft/packages/lib/formulas/prepend/formula.json
{
  "$schema": "../../schemas/libFormula.schema.json",
  "name": "Prepend",
  "description": "Add an element to the start of an Array.",
  "arguments": [
    {
      "name": "Array",
      "type": {
        "type": "Array"
      },
      "description": "The Array to prepend to.",
      "formula": {
        "type": "array",
        "arguments": []
      }
    },
    {
      "name": "Item",
      "type": {
        "type": "Any"
      },
      "description": "The item to prepend to the Array.",
      "formula": {
        "type": "value",
        "value": "Item"
      }
    }
  ],
  "output": {
    "description": "A new Array containing the new item and all the elements from the input Array.",
    "type": {
      "type": "Array"
    }
  }
}

=== nordcraftengine/nordcraft/packages/lib/formulas/roundUp/formula.json
{
  "$schema": "../../schemas/libFormula.schema.json",
  "name": "Round up",
  "description": "Round a Number up to the nearest decimal point.",
  "arguments": [
    {
      "name": "Input",
      "description": "Number to round up.",
      "type": {
        "type": "Number"
      },
      "formula": {
        "type": "value",
        "value": 1
      }
    },
    {
      "name": "Decimals",
      "description": "Number of decimals to round to.",
      "type": {
        "type": "Number"
      },
      "formula": {
        "type": "value",
        "value": 0
      }
    }
  ],
  "output": {
    "type": {
      "type": "Number"
    },
    "description": "The rounded Number."
  }
}

=== nordcraftengine/nordcraft/packages/lib/formulas/drop/formula.json
{
  "$schema": "../../schemas/libFormula.schema.json",
  "name": "Drop",
  "description": "Remove items from the beginning of an Array or String.",
  "arguments": [
    {
      "name": "Array",
      "formula": {
        "type": "value",
        "value": null
      },
      "description": "The input value.",
      "type": {
        "type": "Array \\| String"
      }
    },
    {
      "name": "Count",
      "description": "Number of items to remove.",
      "type": {
        "type": "Number"
      },
      "formula": {
        "type": "value",
        "value": 1
      }
    }
  ],
  "output": {
    "description": "A copy of the list without the first items.",
    "type": {
      "type": "Array \\| String"
    }
  }
}

=== nordcraftengine/nordcraft/packages/lib/formulas/greaterOrEqueal/formula.json
{
  "$schema": "../../schemas/libFormula.schema.json",
  "name": "Greater or equal",
  "description": "Compute whether a value is larger than or equal to another value.",
  "arguments": [
    {
      "name": "First",
      "formula": {
        "type": "value",
        "value": ""
      },
      "description": "First value to be compared.",
      "type": {
        "type": "Number"
      }
    },
    {
      "name": "Second",
      "formula": {
        "type": "value",
        "value": ""
      },
      "description": "Second value to be compared.",
      "type": {
        "type": "Number"
      }
    }
  ],
  "output": {
    "description": "Returns True if the first Number is larger than or equal to the second Number.",
    "type": {
      "type": "Boolean"
    }
  }
}

=== nordcraftengine/nordcraft/packages/lib/formulas/size/formula.json
{
  "$schema": "../../schemas/libFormula.schema.json",
  "name": "Size",
  "description": "Get the size of an Array, Object or String.",
  "arguments": [
    {
      "name": "Collection",
      "formula": {
        "type": "value",
        "value": [1, 2, 3]
      },
      "description": "The collection to get the size of.",
      "type": {
        "type": "Array \\| Object \\| String"
      }
    }
  ],
  "output": {
    "description": "The size of the collection.",
    "type": {
      "type": "Number"
    }
  }
}

=== nordcraftengine/nordcraft/packages/lib/formulas/dateFromTimestamp/formula.json
{
  "$schema": "../../schemas/libFormula.schema.json",
  "name": "Date From Timestamp",
  "arguments": [
    {
      "name": "Timestamp",
      "description": "A Number in milliseconds since 1st January, 1970 (EPOCH).",
      "type": {
        "type": "Number"
      },
      "formula": {
        "type": "value",
        "value": 1687787245933
      }
    }
  ],
  "description": "Convert a timestamp (milliseconds) to a Date.",
  "output": {
    "description": "The input value converted to a Date.",
    "type": {
      "type": "Date"
    }
  }
}
